site_name: InvoiceBldr
extra_css: [extra.css]
nav:
  - Home: index.md
  - Technical Guide: tech.md
  - Cloud Infrastructure: cloud.md
  - Release Notes: release-notes.md
theme: readthedocs
markdown_extensions:
  - toc:
      separator: "-"
